In [2]:
import numpy as np
import sympy as smp
import symengine as sme
from sympy.printing import pycode

In [3]:
def Skerr_riemann_tensor(r, theta, a, Delta, Sigma, M=1.0, config="ulll"):
    """
    Define variables

    Components of the Riemann tensor for Kerr Metric
    From Reference Paper, Appendix
    The Configuration is ulll
    """

    rijkl = np.zeros((4, 4, 4, 4), dtype=type(r))

    # Definitions
    # Delta = a**2 - 2.0 * M * r + r**2
    # Sigma = r**2 + a**2 * sme.cos(theta) ** 2

    rijkl[0, 0, 0, 3] = (
        2.0
        * M**2
        * sme.sin(theta) ** 2
        * a
        * r**2
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        / Sigma**4
    )

    rijkl[0, 0, 1, 2] = (
        -2.0
        * M**2
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * r
        * sme.cos(theta)
        * a**2
        * sme.sin(theta)
        / (Sigma**3 * Delta)
    )

    rijkl[0, 1, 0, 1] = (
        M
        * r
        * (2.0 * (r**2 + a**2) + a**2 * sme.sin(theta) ** 2)
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        / (Sigma**3 * Delta)
    )

    rijkl[0, 1, 0, 2] = (
        -M
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * (3.0 * (r**2 + a**2) - 2 * M * r)
        * a**2
        * sme.sin(theta)
        * sme.cos(theta)
        / (Sigma**3 * Delta)
    )

    rijkl[0, 1, 1, 3] = (
        3.0
        * M
        * sme.sin(theta) ** 2
        * a
        * r
        * (r**2 + a**2)
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        / (Sigma**3 * Delta)
    )

    rijkl[0, 1, 2, 3] = (
        -M
        * sme.cos(theta)
        * sme.sin(theta)
        * a
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * (2.0 * (r**2 + a**2) ** 2 + a**2 * sme.sin(theta) ** 2 * Delta)
        / (Sigma**3 * Delta)
    )

    # Antisymmetric under exchange of last two indices.
    rijkl[0, 0, 3, 0] = -rijkl[0, 0, 0, 3]
    rijkl[0, 0, 2, 1] = -rijkl[0, 0, 1, 2]
    rijkl[0, 1, 1, 0] = -rijkl[0, 1, 0, 1]
    rijkl[0, 1, 2, 0] = -rijkl[0, 1, 0, 2]
    rijkl[0, 1, 3, 1] = -rijkl[0, 1, 1, 3]
    rijkl[0, 1, 3, 2] = -rijkl[0, 1, 2, 3]

    #! -------------------------------------------------------------------------------------#

    rijkl[0, 2, 0, 1] = (
        -M
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * (3.0 * (r**2 + a**2) - 4 * M * r)
        * a**2
        * sme.sin(theta)
        * sme.cos(theta)
        / (Sigma**3 * Delta)
    )
    rijkl[0, 2, 0, 2] = (
        -M
        * r
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * (r**2 + a**2 + 2 * a**2 * sme.sin(theta) ** 2)
        / Sigma**3
    )
    rijkl[0, 2, 1, 3] = (
        -M
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * ((a**2 + r**2) ** 2 + 2.0 * a**2 * sme.sin(theta) ** 2 * Delta)
        * a
        * sme.sin(theta)
        * sme.cos(theta)
        / (Sigma**3 * Delta)
    )
    rijkl[0, 2, 2, 3] = (
        -3.0
        * M
        * sme.sin(theta) ** 2
        * r
        * a
        * (a**2 + r**2)
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        / Sigma**3
    )
    rijkl[0, 3, 0, 3] = (
        -sme.sin(theta) ** 2
        * M
        * r
        * (r**2 + 3 * a**2 * sme.sin(theta) ** 2 - 3 * a**2)
        * ((a**2 + r**2) ** 2 - a**2 * sme.sin(theta) ** 2 * Delta)
        / Sigma**4
    )
    rijkl[0, 3, 1, 2] = (
        (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * M
        * ((a**2 + r**2) ** 2 - a**2 * sme.sin(theta) ** 2 * Delta)
        * a
        * sme.sin(theta)
        * sme.cos(theta)
        / (Sigma**3 * Delta)
    )

    # Symmetries
    rijkl[0, 2, 1, 0] = -rijkl[0, 2, 0, 1]
    rijkl[0, 2, 2, 0] = -rijkl[0, 2, 0, 2]
    rijkl[0, 2, 3, 1] = -rijkl[0, 2, 1, 3]
    rijkl[0, 2, 3, 2] = -rijkl[0, 2, 2, 3]
    rijkl[0, 3, 3, 0] = -rijkl[0, 3, 0, 3]
    rijkl[0, 3, 2, 1] = -rijkl[0, 3, 1, 2]

    #! ------------------------------------------------------------------------------#

    rijkl[1, 0, 0, 1] = (
        r
        * M
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * (a**2 * sme.sin(theta) ** 2 + 2.0 * Delta)
        / Sigma**4
    )
    rijkl[1, 0, 0, 2] = (
        -3.0
        * M
        * Delta
        * a**2
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * sme.sin(theta)
        * sme.cos(theta)
        / Sigma**4
    )
    rijkl[1, 0, 1, 3] = (
        r
        * M
        * a
        * (3.0 * (r**2 + a**2) - 4.0 * M * r)
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * sme.sin(theta) ** 2
        / Sigma**4
    )
    rijkl[1, 0, 2, 3] = (
        -a
        * M
        * (2.0 * (r**2 + a**2) + a**2 * sme.sin(theta) ** 2)
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * Delta
        * sme.cos(theta)
        * sme.sin(theta)
        / Sigma**4
    )
    rijkl[1, 2, 0, 3] = (
        -sme.cos(theta)
        * M
        * sme.sin(theta)
        * a
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * Delta
        / Sigma**3
    )
    rijkl[1, 2, 1, 2] = -M * r * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2) / Sigma**2
    rijkl[1, 3, 0, 1] = (
        -sme.sin(theta) ** 2
        * M
        * r
        * a
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * (3.0 * (r**2 + a**2) - 4.0 * M * r)
        / Sigma**4
    )
    rijkl[1, 3, 0, 2] = (
        a
        * M
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * (r**2 + a**2 + 2.0 * a**2 * sme.sin(theta) ** 2)
        * Delta
        * sme.cos(theta)
        * sme.sin(theta)
        / Sigma**4
    )
    rijkl[1, 3, 1, 3] = (
        -sme.sin(theta) ** 2
        * M
        * r
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * ((r**2 + a**2) ** 2 + 2.0 * a**2 * Delta * sme.sin(theta) ** 2)
        / Sigma**4
    )
    rijkl[1, 3, 2, 3] = (
        3.0
        * M
        * a**2
        * (r**2 + a**2)
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * Delta
        * sme.cos(theta)
        * sme.sin(theta) ** 3
        / Sigma**4
    )

    # Symmetries
    rijkl[1, 0, 1, 0] = -rijkl[1, 0, 0, 1]
    rijkl[1, 0, 2, 0] = -rijkl[1, 0, 0, 2]
    rijkl[1, 0, 3, 1] = -rijkl[1, 0, 1, 3]
    rijkl[1, 0, 3, 2] = -rijkl[1, 0, 2, 3]
    rijkl[1, 2, 3, 0] = -rijkl[1, 2, 0, 3]
    rijkl[1, 2, 2, 1] = -rijkl[1, 2, 1, 2]
    rijkl[1, 3, 1, 0] = -rijkl[1, 3, 0, 1]
    rijkl[1, 3, 2, 0] = -rijkl[1, 3, 0, 2]
    rijkl[1, 3, 3, 1] = -rijkl[1, 3, 1, 3]
    rijkl[1, 3, 3, 2] = -rijkl[1, 3, 2, 3]

    #! -------------------------------------------------------------------------------------#

    rijkl[2, 0, 0, 1] = (
        -3.0
        * M
        * a**2
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * sme.sin(theta)
        * sme.cos(theta)
        / Sigma**4
    )
    rijkl[2, 0, 0, 2] = (
        -M
        * r
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * (2.0 * a**2 * sme.sin(theta) ** 2 + Delta)
        / Sigma**4
    )
    rijkl[2, 0, 1, 3] = (
        -a
        * M
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * (r**2 + a**2 + 2.0 * a**2 * sme.sin(theta) ** 2)
        * sme.cos(theta)
        * sme.sin(theta)
        / Sigma**4
    )
    rijkl[2, 0, 2, 3] = (
        -M
        * r
        * a
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * (3.0 * (r**2 + a**2) - 2.0 * M * r)
        * sme.sin(theta) ** 2
        / Sigma**4
    )
    rijkl[2, 1, 0, 3] = (
        M
        * a
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * sme.cos(theta)
        * sme.sin(theta)
        / Sigma**3
    )
    rijkl[2, 1, 1, 2] = (
        M * r * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2) / (Delta * Sigma**2)
    )
    rijkl[2, 3, 0, 1] = (
        M
        * a
        * (2.0 * (r**2 + a**2) + a**2 * sme.sin(theta) ** 2)
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * sme.cos(theta)
        * sme.sin(theta)
        / Sigma**4
    )
    rijkl[2, 3, 0, 2] = (
        M
        * r
        * a
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * (3.0 * (r**2 + a**2) - 2.0 * M * r)
        * sme.sin(theta) ** 2
        / Sigma**4
    )
    rijkl[2, 3, 1, 3] = (
        3.0
        * M
        * a**2
        * (r**2 + a**2)
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * sme.cos(theta)
        * sme.sin(theta) ** 3
        / Sigma**4
    )
    rijkl[2, 3, 2, 3] = (
        M
        * r
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * (2.0 * (r**2 + a**2) ** 2 + a**2 * Delta * sme.sin(theta) ** 2)
        * sme.sin(theta) ** 2
        / Sigma**4
    )

    # Symmetries
    rijkl[2, 0, 1, 0] = -rijkl[2, 0, 0, 1]
    rijkl[2, 0, 2, 0] = -rijkl[2, 0, 0, 2]
    rijkl[2, 0, 3, 1] = -rijkl[2, 0, 1, 3]
    rijkl[2, 0, 3, 2] = -rijkl[2, 0, 2, 3]
    rijkl[2, 1, 3, 0] = -rijkl[2, 1, 0, 3]
    rijkl[2, 1, 2, 1] = -rijkl[2, 1, 1, 2]
    rijkl[2, 3, 1, 0] = -rijkl[2, 3, 0, 1]
    rijkl[2, 3, 2, 0] = -rijkl[2, 3, 0, 2]
    # rijkl[2, 3, 2, 1] = -rijkl[2, 3, 1, 2]
    rijkl[2, 3, 3, 1] = -rijkl[2, 3, 1, 3]
    rijkl[2, 3, 3, 2] = -rijkl[2, 3, 2, 3]

    #! --------------------------------------------------------------------------#

    rijkl[3, 0, 1, 2] = (
        -M
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * (a**2 * sme.sin(theta) ** 2 - Delta)
        * a
        * (sme.cos(theta) / sme.sin(theta))
        / (Delta * Sigma**3)
    )
    rijkl[3, 1, 0, 1] = (
        3.0 * M * r * a * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2) / (Delta * Sigma**3)
    )
    rijkl[3, 1, 0, 2] = (
        -M
        * a
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * (2.0 * a**2 * sme.sin(theta) ** 2 + Delta)
        * (sme.cos(theta) / sme.sin(theta))
        / (Delta * Sigma**3)
    )
    rijkl[3, 1, 1, 3] = (
        M
        * r
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * (r**2 + a**2 + 2.0 * a**2 * sme.sin(theta) ** 2)
        / (Delta * Sigma**3)
    )
    rijkl[3, 1, 2, 3] = (
        -M
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * (3.0 * (r**2 + a**2) - 2.0 * M * r)
        * a**2
        * sme.sin(theta)
        * sme.cos(theta)
        / (Delta * Sigma**3)
    )
    rijkl[3, 2, 0, 1] = (
        -M
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * (a**2 * sme.sin(theta) ** 2 + 2.0 * Delta)
        * a
        * (sme.cos(theta) / sme.sin(theta))
        / (Delta * Sigma**3)
    )
    rijkl[3, 2, 0, 2] = (
        -M * 3.0 * r * a * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2) / Sigma**3
    )
    rijkl[3, 2, 1, 3] = (
        -M
        * a**2
        * (3 * r**2 - a**2 * sme.cos(theta) ** 2)
        * (3.0 * (r**2 + a**2) - 4.0 * M * r)
        * sme.sin(theta)
        * sme.cos(theta)
        / (Delta * Sigma**3)
    )
    rijkl[3, 2, 2, 3] = (
        -M
        * r
        * (2.0 * (r**2 + a**2) + a**2 * sme.sin(theta) ** 2)
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        / Sigma**3
    )
    rijkl[3, 3, 0, 3] = (
        -2.0
        * M**2
        * a
        * r**2
        * (r**2 - 3.0 * a**2 * sme.cos(theta) ** 2)
        * sme.sin(theta) ** 2
        / Sigma**4
    )
    rijkl[3, 3, 1, 2] = (
        2.0
        * M**2
        * r
        * a**2
        * (3.0 * r**2 - a**2 * sme.cos(theta) ** 2)
        * sme.cos(theta)
        * sme.sin(theta)
        / (Delta * Sigma**3)
    )

    # Symmetries
    rijkl[3, 0, 2, 1] = -rijkl[3, 0, 1, 2]
    rijkl[3, 1, 1, 0] = -rijkl[3, 1, 0, 1]
    rijkl[3, 1, 2, 0] = -rijkl[3, 1, 0, 2]
    rijkl[3, 1, 3, 1] = -rijkl[3, 1, 1, 3]
    rijkl[3, 1, 3, 2] = -rijkl[3, 1, 2, 3]
    rijkl[3, 2, 1, 0] = -rijkl[3, 2, 0, 1]
    rijkl[3, 2, 2, 0] = -rijkl[3, 2, 0, 2]
    rijkl[3, 2, 3, 1] = -rijkl[3, 2, 1, 3]
    rijkl[3, 2, 3, 2] = -rijkl[3, 2, 2, 3]
    rijkl[3, 3, 3, 0] = -rijkl[3, 3, 0, 3]
    rijkl[3, 3, 2, 1] = -rijkl[3, 3, 1, 2]

    #!---------------------------------------------------------------------#

    part1 = a**2 + 2 * r * (-2 * M + r) + a**2 * sme.cos(2 * theta)
    part2 = 3 * a**2 - 2 * r**2 + 3 * a**2 * sme.cos(2 * theta)
    part3 = (a**2 + 2 * r**2 + a**2 * sme.cos(2 * theta)) ** 4
    # Calculating Rtensor elements

    # rijkl[3, 0, 0, 3] =  (part1 + part2 + part3 + part4) / (Sigma**5)
    rijkl[3, 0, 0, 3] = 4 * M * r * part1 * part2 / part3
    rijkl[3, 0, 3, 0] = -rijkl[3, 0, 0, 3]

    # return rijkl
    if config == "ulll":
        return rijkl + np.zeros((4, 4, 4, 4))

    elif config == "llll":
        gk = cov_metric_tensor(r=r, theta=theta, a=a, M=M)
        return np.einsum("ij,jklm->iklm", gk, rijkl) + np.zeros((4, 4, 4, 4))

    # elif config=="lluu":
    #     #!Config: lluu
    #     gkinv = cot_metric_tensor(r=r, theta=theta, a=a, M=M)
    #     gk = cov_metric_tensor(r=r, theta=theta, a=a, M=M)
    #     rllll = np.einsum("ij,jklm->iklm", gk, rijkl)

    #     return np.einsum("kjlm,la,mb->kjab", rllll, gkinv, gkinv)

    else:
        return "Invalid String"

In [4]:
def DRijkl(r,theta,a, M=1.0, config="ullll"):

    drijkl= np.zeros((4,4,4,4,4),dtype=type(r))

    Delta=  a**2 - 2 * M * r + r**2
    Sigma =  r**2 + a**2 * np.cos(theta) ** 2
    dSt= -a**2*np.sin(2*theta)
    dSr=  2*r
    dD=  2*(r-M)

    drijkl[0, 0, 0, 3, :] = [0, M**2*a*r*(8.0*r*(3.0*a**2*np.cos(theta)**2 - r**2)*dSr + 4.0*(-3.0*a**2*np.cos(theta)**2 + 2.0*r**2)*Sigma)*np.sin(theta)**2/Sigma**5, M**2*a*r**2*(-3.0*a**2*Sigma*np.sin(4*theta) - 3.0*a**2*dSt*np.cos(4*theta) + 3.0*a**2*dSt + 2.0*r**2*Sigma*np.sin(2*theta) + 4.0*r**2*dSt*np.cos(2*theta) - 4.0*r**2*dSt)/Sigma**5, 0.]

    drijkl[0, 0, 1, 2, :] = [0, M**2*a**2*(-6.0*r*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*dSr - 2.0*r*(a**2*np.cos(theta)**2 - 3.0*r**2)*Sigma*dD + (2.0*a**2*np.cos(theta)**2 - 18.0*r**2)*Delta*Sigma)*np.sin(theta)*np.cos(theta)/(Delta**2*Sigma**4), M**2*a**2*r*(-6.0*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (8.0*a**2*np.sin(theta)**4 - 10.0*a**2*np.sin(theta)**2 + 2.0*a**2 + 12.0*r**2*np.sin(theta)**2 - 6.0*r**2)*Sigma)/(Delta*Sigma**4), 0.]

    drijkl[0, 1, 0, 1, :] = [0, M*(3*r*(3.0*a**2*np.cos(theta)**2 - r**2)*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*Delta*dSr + r*(3.0*a**2*np.cos(theta)**2 - r**2)*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*Sigma*dD + (3.0*a**4*np.sin(theta)**4 + 3.0*a**4*np.sin(theta)**2 - 6.0*a**4 + 21.0*a**2*r**2*np.sin(theta)**2 - 12.0*a**2*r**2 + 10.0*r**4)*Delta*Sigma)/(Delta**2*Sigma**4), M*r*(a**2*(12.0*a**2*np.sin(theta)**2 + 6.0*a**2 + 14.0*r**2)*Sigma*np.sin(theta)*np.cos(theta) + 3*(3.0*a**2*np.cos(theta)**2 - r**2)*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*dSt)/(Delta*Sigma**4), 0.]

    drijkl[0, 1, 0, 2, :] = [0, M*a**2*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*(-2*M*r + 3.0*a**2 + 3.0*r**2)*Delta*dSr - (a**2*np.cos(theta)**2 - 3.0*r**2)*(-2*M*r + 3.0*a**2 + 3.0*r**2)*Sigma*dD + (-6.0*r*(-2*M*r + 3.0*a**2 + 3.0*r**2) + (-2*M + 6.0*r)*(a**2*np.cos(theta)**2 - 3.0*r**2))*Delta*Sigma)*np.sin(theta)*np.cos(theta)/(Delta**2*Sigma**4), M*a**2*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (4.0*a**2*np.sin(theta)**4 - 5.0*a**2*np.sin(theta)**2 + 1.0*a**2 + 6.0*r**2*np.sin(theta)**2 - 3.0*r**2)*Sigma)*(-2*M*r + 3.0*a**2 + 3.0*r**2)/(Delta*Sigma**4), 0.]

    drijkl[0, 1, 1, 3, :] = [0, M*a*(9.0*r*(a**2 + r**2)*(3.0*a**2*np.cos(theta)**2 - r**2)*Delta*dSr + 3.0*r*(a**2 + r**2)*(3.0*a**2*np.cos(theta)**2 - r**2)*Sigma*dD + (-9.0*a**4*np.cos(theta)**2 - 27.0*a**2*r**2*np.cos(theta)**2 + 9.0*a**2*r**2 + 15.0*r**4)*Delta*Sigma)*np.sin(theta)**2/(Delta**2*Sigma**4), M*a*r*(a**2 + r**2)*(-4.5*a**2*Sigma*np.sin(4*theta) - 3.375*a**2*dSt*np.cos(4*theta) + 3.375*a**2*dSt + 3.0*r**2*Sigma*np.sin(2*theta) + 4.5*r**2*dSt*np.cos(2*theta) - 4.5*r**2*dSt)/(Delta*Sigma**4), 0.]

    drijkl[0, 1, 2, 3, :] = [0., M*a*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2)*Delta*dSr - (a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2)*Sigma*dD + (-6.0*r*(a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2) + (a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*dD*np.sin(theta)**2 + 8.0*r*(a**2 + r**2)))*Delta*Sigma)*np.sin(theta)*np.cos(theta)/(Delta**2*Sigma**4), M*a*(2*a**2*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*Sigma*np.sin(theta)**2*np.cos(theta)**2 - 3*(a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2)*dSt*np.sin(theta)*np.cos(theta) + (a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2)*(4.0*a**2*np.sin(theta)**4 - 5.0*a**2*np.sin(theta)**2 + 1.0*a**2 + 6.0*r**2*np.sin(theta)**2 - 3.0*r**2)*Sigma)/(Delta*Sigma**4), 0.]

    # Antisymmetric under exchange of last two indices.
    drijkl[0, 0, 3, 0, :] = -drijkl[0, 0, 0, 3, :]
    drijkl[0, 0, 2, 1, :] = -drijkl[0, 0, 1, 2, :]
    drijkl[0, 1, 1, 0, :] = -drijkl[0, 1, 0, 1, :]
    drijkl[0, 1, 2, 0, :] = -drijkl[0, 1, 0, 2, :]
    drijkl[0, 1, 3, 1, :] = -drijkl[0, 1, 1, 3, :]
    drijkl[0, 1, 3, 2, :] = -drijkl[0, 1, 2, 3, :]

    #! -------------------------------------------------------------------------------------#

    drijkl[0, 2, 0, 1, :] = [0., M*a**2*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*(-4*M*r + 3.0*a**2 + 3.0*r**2)*Delta*dSr - (a**2*np.cos(theta)**2 - 3.0*r**2)*(-4*M*r + 3.0*a**2 + 3.0*r**2)*Sigma*dD + (-6.0*r*(-4*M*r + 3.0*a**2 + 3.0*r**2) + (-4*M + 6.0*r)*(a**2*np.cos(theta)**2 - 3.0*r**2))*Delta*Sigma)*np.sin(theta)*np.cos(theta)/(Delta**2*Sigma**4), M*a**2*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (4.0*a**2*np.sin(theta)**4 - 5.0*a**2*np.sin(theta)**2 + 1.0*a**2 + 6.0*r**2*np.sin(theta)**2 - 3.0*r**2)*Sigma)*(-4*M*r + 3.0*a**2 + 3.0*r**2)/(Delta*Sigma**4), 0.]

    drijkl[0, 2, 0, 2, :] = [0., M*(-3*r*(3.0*a**2*np.cos(theta)**2 - r**2)*(2*a**2*np.sin(theta)**2 + a**2 + r**2)*dSr + (-6.0*a**4*np.sin(theta)**4 + 3.0*a**4*np.sin(theta)**2 + 3.0*a**4 - 15.0*a**2*r**2*np.sin(theta)**2 + 6.0*a**2*r**2 - 5.0*r**4)*Sigma)/Sigma**4, M*r*(a**2*(-24.0*a**2*np.sin(theta)**2 + 6.0*a**2 - 10.0*r**2)*Sigma*np.sin(theta)*np.cos(theta) - 3*(3.0*a**2*np.cos(theta)**2 - r**2)*(2*a**2*np.sin(theta)**2 + a**2 + r**2)*dSt)/Sigma**4, 0.]

    drijkl[0, 2, 1, 3, :] = [0., M*a*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*(2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2)*Delta*dSr - (a**2*np.cos(theta)**2 - 3.0*r**2)*(2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2)*Sigma*dD + (-6.0*r*(2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2) + (a**2*np.cos(theta)**2 - 3.0*r**2)*(2.0*a**2*dD*np.sin(theta)**2 + 4*r*(a**2 + r**2)))*Delta*Sigma)*np.sin(theta)*np.cos(theta)/(Delta**2*Sigma**4), M*a*(4.0*a**2*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*Sigma*np.sin(theta)**2*np.cos(theta)**2 - 3*(a**2*np.cos(theta)**2 - 3.0*r**2)*(2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2)*dSt*np.sin(theta)*np.cos(theta) + (2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2)*(4.0*a**2*np.sin(theta)**4 - 5.0*a**2*np.sin(theta)**2 + 1.0*a**2 + 6.0*r**2*np.sin(theta)**2 - 3.0*r**2)*Sigma)/(Delta*Sigma**4), 0.]

    drijkl[0, 2, 2, 3, :] = [0., M*a*(-9.0*r*(a**2 + r**2)*(3.0*a**2*np.cos(theta)**2 - r**2)*dSr + (9.0*a**4*np.cos(theta)**2 + 27.0*a**2*r**2*np.cos(theta)**2 - 9.0*a**2*r**2 - 15.0*r**4)*Sigma)*np.sin(theta)**2/Sigma**4, M*a*r*(a**2 + r**2)*(4.5*a**2*Sigma*np.sin(4*theta) + 3.375*a**2*dSt*np.cos(4*theta) - 3.375*a**2*dSt - 3.0*r**2*Sigma*np.sin(2*theta) - 4.5*r**2*dSt*np.cos(2*theta) + 4.5*r**2*dSt)/Sigma**4, 0.]

    drijkl[0, 3, 0, 3, :] = [0., M*(-4*r*(-3*a**2*np.cos(theta)**2 + r**2)*(a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2)*dSr + (2*r**2*(a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2) + r*(-3*a**2*np.cos(theta)**2 + r**2)*(a**2*dD*np.sin(theta)**2 - 4*r*(a**2 + r**2)) + (-3*a**2*np.cos(theta)**2 + r**2)*(a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2))*Sigma)*np.sin(theta)**2/Sigma**5, 2*M*r*(-2*(-3*a**2*np.cos(theta)**2 + r**2)*(a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2)*dSt*np.sin(theta) + (a**2*(-3*a**2*np.cos(theta)**2 + r**2)*Delta*np.sin(theta)**2 + 3*a**2*(a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2)*np.sin(theta)**2 + (-3*a**2*np.cos(theta)**2 + r**2)*(a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2))*Sigma*np.cos(theta))*np.sin(theta)/Sigma**5, 0.]

    drijkl[0, 3, 1, 2, :] = [0., M*a*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2)*Delta*dSr - (a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2)*Sigma*dD + (-6.0*r*(a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2) + (a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*dD*np.sin(theta)**2 - 4*r*(a**2 + r**2)))*Delta*Sigma)*np.sin(theta)*np.cos(theta)/(Delta**2*Sigma**4), M*a*(2*a**2*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*Sigma*np.sin(theta)**2*np.cos(theta)**2 - 3*(a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2)*dSt*np.sin(theta)*np.cos(theta) + (a**2*Delta*np.sin(theta)**2 - (a**2 + r**2)**2)*(4.0*a**2*np.sin(theta)**4 - 5.0*a**2*np.sin(theta)**2 + 1.0*a**2 + 6.0*r**2*np.sin(theta)**2 - 3.0*r**2)*Sigma)/(Delta*Sigma**4), 0.]

    # Symmetries
    drijkl[0, 2, 1, 0, :] = -drijkl[0, 2, 0, 1, :]
    drijkl[0, 2, 2, 0, :] = -drijkl[0, 2, 0, 2, :]
    drijkl[0, 2, 3, 1, :] = -drijkl[0, 2, 1, 3, :]
    drijkl[0, 2, 3, 2, :] = -drijkl[0, 2, 2, 3, :]
    drijkl[0, 3, 3, 0, :] = -drijkl[0, 3, 0, 3, :]
    drijkl[0, 3, 2, 1, :] = -drijkl[0, 3, 1, 2, :]

    #! ------------------------------------------------------------------------------#

    drijkl[1, 0, 0, 1, :] = [0., M*(4*r*(a**2*np.sin(theta)**2 + 2.0*Delta)*(3.0*a**2*np.cos(theta)**2 - r**2)*dSr + (2*r**2*(a**2*np.sin(theta)**2 + 2.0*Delta) - 2.0*r*(3.0*a**2*np.cos(theta)**2 - r**2)*dD - (a**2*np.sin(theta)**2 + 2.0*Delta)*(3.0*a**2*np.cos(theta)**2 - r**2))*Sigma)/Sigma**5, M*r*(a**2*(12.0*a**2*np.sin(theta)**2 - 6.0*a**2 + 2.0*r**2 + 12.0*Delta)*Sigma*np.sin(theta)*np.cos(theta) + 4*(a**2*np.sin(theta)**2 + 2.0*Delta)*(3.0*a**2*np.cos(theta)**2 - r**2)*dSt)/Sigma**5, 0.]

    drijkl[1, 0, 0, 2, :] = [0., M*a**2*(-12.0*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*dSr + (-18.0*r*Delta + 3.0*(a**2*np.cos(theta)**2 - 3.0*r**2)*dD)*Sigma)*np.sin(theta)*np.cos(theta)/Sigma**5, M*a**2*(-12.0*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (12.0*a**2*np.sin(theta)**4 - 15.0*a**2*np.sin(theta)**2 + 3.0*a**2 + 18.0*r**2*np.sin(theta)**2 - 9.0*r**2)*Sigma)*Delta/Sigma**5, 0.]

    drijkl[1, 0, 1, 3, :] = [0., M*a*(4*r*(3.0*a**2*np.cos(theta)**2 - r**2)*(-4.0*M*r + 3.0*a**2 + 3.0*r**2)*dSr + (r**2*(-8.0*M*r + 6.0*a**2 + 6.0*r**2) + r*(4.0*M - 6.0*r)*(3.0*a**2*np.cos(theta)**2 - r**2) + (3.0*a**2*np.cos(theta)**2 - r**2)*(4.0*M*r - 3.0*a**2 - 3.0*r**2))*Sigma)*np.sin(theta)**2/Sigma**5, M*a*r*(-4.0*M*r + 3.0*a**2 + 3.0*r**2)*(-1.5*a**2*Sigma*np.sin(4*theta) - 1.5*a**2*dSt*np.cos(4*theta) + 1.5*a**2*dSt + r**2*Sigma*np.sin(2*theta) + 2.0*r**2*dSt*np.cos(2*theta) - 2.0*r**2*dSt)/Sigma**5, 0.]

    drijkl[1, 0, 2, 3, :] = [0., M*a*(-4*(a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*Delta*dSr + (4.0*r*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta - 6.0*r*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*Delta + (a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*dD)*Sigma)*np.sin(theta)*np.cos(theta)/Sigma**5, M*a*(-4*(a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (6.0*a**4*np.sin(theta)**6 - 1.0*a**4*np.sin(theta)**4 - 7.0*a**4*np.sin(theta)**2 + 2.0*a**4 + 20.0*a**2*r**2*np.sin(theta)**4 - 7.0*a**2*r**2*np.sin(theta)**2 - 4.0*a**2*r**2 + 12.0*r**4*np.sin(theta)**2 - 6.0*r**4)*Sigma)*Delta/Sigma**5, 0.]

    drijkl[1, 2, 0, 3, :] = [0., M*a*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*dSr + (-6.0*r*Delta + (a**2*np.cos(theta)**2 - 3.0*r**2)*dD)*Sigma)*np.sin(theta)*np.cos(theta)/Sigma**4, M*a*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (4.0*a**2*np.sin(theta)**4 - 5.0*a**2*np.sin(theta)**2 + 1.0*a**2 + 6.0*r**2*np.sin(theta)**2 - 3.0*r**2)*Sigma)*Delta/Sigma**4, 0.]

    drijkl[1, 2, 1, 2, :] = [0., M*(-2*r*(3.0*a**2*np.cos(theta)**2 - r**2)*dSr + 3.0*(a**2*np.cos(theta)**2 - r**2)*Sigma)/Sigma**3, M*r*(-3.0*a**2*Sigma*np.sin(2*theta) - 2*(3.0*a**2*np.cos(theta)**2 - r**2)*dSt)/Sigma**3, 0.]

    drijkl[1, 3, 0, 1, :] = [0., M*a*(-4*r*(3.0*a**2*np.cos(theta)**2 - r**2)*(-4.0*M*r + 3.0*a**2 + 3.0*r**2)*dSr + (r**2*(8.0*M*r - 6.0*a**2 - 6.0*r**2) - r*(4.0*M - 6.0*r)*(3.0*a**2*np.cos(theta)**2 - r**2) + (3.0*a**2*np.cos(theta)**2 - r**2)*(-4.0*M*r + 3.0*a**2 + 3.0*r**2))*Sigma)*np.sin(theta)**2/Sigma**5, M*a*r*(-4.0*M*r + 3.0*a**2 + 3.0*r**2)*(1.5*a**2*Sigma*np.sin(4*theta) + 1.5*a**2*dSt*np.cos(4*theta) - 1.5*a**2*dSt - 1.0*r**2*Sigma*np.sin(2*theta) - 2.0*r**2*dSt*np.cos(2*theta) + 2.0*r**2*dSt)/Sigma**5, 0.]

    drijkl[1, 3, 0, 2, :] = [0., M*a*(4*(a**2*np.cos(theta)**2 - 3.0*r**2)*(2.0*a**2*np.sin(theta)**2 + a**2 + r**2)*Delta*dSr + (-2*r*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta + 6.0*r*(2.0*a**2*np.sin(theta)**2 + a**2 + r**2)*Delta - (a**2*np.cos(theta)**2 - 3.0*r**2)*(2.0*a**2*np.sin(theta)**2 + a**2 + r**2)*dD)*Sigma)*np.sin(theta)*np.cos(theta)/Sigma**5, M*a*(4*(a**2*np.cos(theta)**2 - 3.0*r**2)*(2.0*a**2*np.sin(theta)**2 + a**2 + r**2)*dSt*np.sin(theta)*np.cos(theta) + (-12.0*a**4*np.sin(theta)**6 + 14.0*a**4*np.sin(theta)**4 - 1.0*a**4*np.sin(theta)**2 - 1.0*a**4 - 28.0*a**2*r**2*np.sin(theta)**4 + 17.0*a**2*r**2*np.sin(theta)**2 + 2.0*a**2*r**2 - 6.0*r**4*np.sin(theta)**2 + 3.0*r**4)*Sigma)*Delta/Sigma**5, 0.]

    drijkl[1, 3, 1, 3, :] = [0., M*(-4*r*(3.0*a**2*np.cos(theta)**2 - r**2)*(2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2)*dSr + (-2*r**2*(2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2) + r*(3.0*a**2*np.cos(theta)**2 - r**2)*(2.0*a**2*dD*np.sin(theta)**2 + 4*r*(a**2 + r**2)) + (3.0*a**2*np.cos(theta)**2 - r**2)*(2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2))*Sigma)*np.sin(theta)**2/Sigma**5, M*r*(-4*(3.0*a**2*np.cos(theta)**2 - r**2)*(2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2)*dSt*np.sin(theta) + (4.0*a**2*(3.0*a**2*np.cos(theta)**2 - r**2)*Delta*np.sin(theta)**2 - 6.0*a**2*(2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2)*np.sin(theta)**2 + 2*(3.0*a**2*np.cos(theta)**2 - r**2)*(2.0*a**2*Delta*np.sin(theta)**2 + (a**2 + r**2)**2))*Sigma*np.cos(theta))*np.sin(theta)/Sigma**5, 0.]

    drijkl[1, 3, 2, 3, :] = [0., M*a**2*(12.0*(a**2 + r**2)*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*dSr + (18.0*r*(a**2 + r**2)*Delta - 6.0*r*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta - 3.0*(a**2 + r**2)*(a**2*np.cos(theta)**2 - 3.0*r**2)*dD)*Sigma)*np.sin(theta)**3*np.cos(theta)/Sigma**5, M*a**2*(a**2 + r**2)*(12.0*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (-18.0*a**2*np.sin(theta)**4 + 27.0*a**2*np.sin(theta)**2 - 9.0*a**2 - 36.0*r**2*np.sin(theta)**2 + 27.0*r**2)*Sigma)*Delta*np.sin(theta)**2/Sigma**5, 0.]

    # Symmetries
    drijkl[1, 0, 1, 0, :] = -drijkl[1, 0, 0, 1, :]
    drijkl[1, 0, 2, 0, :] = -drijkl[1, 0, 0, 2, :]
    drijkl[1, 0, 3, 1, :] = -drijkl[1, 0, 1, 3, :]
    drijkl[1, 0, 3, 2, :] = -drijkl[1, 0, 2, 3, :]
    drijkl[1, 2, 3, 0, :] = -drijkl[1, 2, 0, 3, :]
    drijkl[1, 2, 2, 1, :] = -drijkl[1, 2, 1, 2, :]
    drijkl[1, 3, 1, 0, :] = -drijkl[1, 3, 0, 1, :]
    drijkl[1, 3, 2, 0, :] = -drijkl[1, 3, 0, 2, :]
    drijkl[1, 3, 3, 1, :] = -drijkl[1, 3, 1, 3, :]
    drijkl[1, 3, 3, 2, :] = -drijkl[1, 3, 2, 3, :]

    #! -------------------------------------------------------------------------------------#

    drijkl[2, 0, 0, 1, :] = [0., M*a**2*(-18.0*r*Sigma - 12.0*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSr)*np.sin(theta)*np.cos(theta)/Sigma**5, M*a**2*(-12.0*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (12.0*a**2*np.sin(theta)**4 - 15.0*a**2*np.sin(theta)**2 + 3.0*a**2 + 18.0*r**2*np.sin(theta)**2 - 9.0*r**2)*Sigma)/Sigma**5, 0.] 

    drijkl[2, 0, 0, 2, :] = [0., M*(-4*r*(2.0*a**2*np.sin(theta)**2 + Delta)*(3.0*a**2*np.cos(theta)**2 - r**2)*dSr + (-2*r**2*(2.0*a**2*np.sin(theta)**2 + Delta) + r*(3.0*a**2*np.cos(theta)**2 - r**2)*dD + (2.0*a**2*np.sin(theta)**2 + Delta)*(3.0*a**2*np.cos(theta)**2 - r**2))*Sigma)/Sigma**5, M*r*(a**2*(-24.0*a**2*np.sin(theta)**2 + 12.0*a**2 - 4.0*r**2 - 6.0*Delta)*Sigma*np.sin(theta)*np.cos(theta) - 4*(2.0*a**2*np.sin(theta)**2 + Delta)*(3.0*a**2*np.cos(theta)**2 - r**2)*dSt)/Sigma**5, 0.]

    drijkl[2, 0, 1, 3, :] = [0., M*a*(r*(14.0*a**2*np.cos(theta)**2 - 18.0*a**2 - 12.0*r**2)*Sigma - 4*(a**2*np.cos(theta)**2 - 3.0*r**2)*(2.0*a**2*np.sin(theta)**2 + a**2 + r**2)*dSr)*np.sin(theta)*np.cos(theta)/Sigma**5, M*a*(-4*(a**2*np.cos(theta)**2 - 3.0*r**2)*(2.0*a**2*np.sin(theta)**2 + a**2 + r**2)*dSt*np.sin(theta)*np.cos(theta) + (12.0*a**4*np.sin(theta)**6 - 14.0*a**4*np.sin(theta)**4 + 1.0*a**4*np.sin(theta)**2 + 1.0*a**4 + 28.0*a**2*r**2*np.sin(theta)**4 - 17.0*a**2*r**2*np.sin(theta)**2 - 2.0*a**2*r**2 + 6.0*r**4*np.sin(theta)**2 - 3.0*r**4)*Sigma)/Sigma**5, 0.]

    drijkl[2, 0, 2, 3, :] = [0., M*a*(-4*r*(3.0*a**2*np.cos(theta)**2 - r**2)*(-2.0*M*r + 3.0*a**2 + 3.0*r**2)*dSr + (r**2*(4.0*M*r - 6.0*a**2 - 6.0*r**2) - r*(2.0*M - 6.0*r)*(3.0*a**2*np.cos(theta)**2 - r**2) + (3.0*a**2*np.cos(theta)**2 - r**2)*(-2.0*M*r + 3.0*a**2 + 3.0*r**2))*Sigma)*np.sin(theta)**2/Sigma**5, M*a*r*(-2.0*M*r + 3.0*a**2 + 3.0*r**2)*(1.5*a**2*Sigma*np.sin(4*theta) + 1.5*a**2*dSt*np.cos(4*theta) - 1.5*a**2*dSt - 1.0*r**2*Sigma*np.sin(2*theta) - 2.0*r**2*dSt*np.cos(2*theta) + 2.0*r**2*dSt)/Sigma**5, 0.]

    drijkl[2, 1, 0, 3, :] = [0., M*a*(6.0*r*Sigma + 3*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSr)*np.sin(theta)*np.cos(theta)/Sigma**4, M*a*(3*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (-4.0*a**2*np.sin(theta)**4 + 5.0*a**2*np.sin(theta)**2 - 1.0*a**2 - 6.0*r**2*np.sin(theta)**2 + 3.0*r**2)*Sigma)/Sigma**4, 0.]

    drijkl[2, 1, 1, 2, :] = [0., M*(2*r*(3.0*a**2*np.cos(theta)**2 - r**2)*Delta*dSr + r*(3.0*a**2*np.cos(theta)**2 - r**2)*Sigma*dD + 3.0*(-a**2*np.cos(theta)**2 + r**2)*Delta*Sigma)/(Delta**2*Sigma**3), M*r*(3.0*a**2*Sigma*np.sin(2*theta) + 2*(3.0*a**2*np.cos(theta)**2 - r**2)*dSt)/(Delta*Sigma**3), 0.]

    drijkl[2, 3, 0, 1, :] = [0., M*a*(r*(10.0*a**2*np.sin(theta)**2 + 8.0*a**2 + 24.0*r**2)*Sigma + 4*(a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*dSr)*np.sin(theta)*np.cos(theta)/Sigma**5, M*a*(4*(a**2*np.cos(theta)**2 - 3.0*r**2)*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (-6.0*a**4*np.sin(theta)**6 + 1.0*a**4*np.sin(theta)**4 + 7.0*a**4*np.sin(theta)**2 - 2.0*a**4 - 20.0*a**2*r**2*np.sin(theta)**4 + 7.0*a**2*r**2*np.sin(theta)**2 + 4.0*a**2*r**2 - 12.0*r**4*np.sin(theta)**2 + 6.0*r**4)*Sigma)/Sigma**5, 0.]

    drijkl[2, 3, 0, 2, :] = [0., M*a*(4*r*(3.0*a**2*np.cos(theta)**2 - r**2)*(-2.0*M*r + 3.0*a**2 + 3.0*r**2)*dSr + (r**2*(-4.0*M*r + 6.0*a**2 + 6.0*r**2) + r*(2.0*M - 6.0*r)*(3.0*a**2*np.cos(theta)**2 - r**2) + (3.0*a**2*np.cos(theta)**2 - r**2)*(2.0*M*r - 3.0*a**2 - 3.0*r**2))*Sigma)*np.sin(theta)**2/Sigma**5, M*a*r*(-2.0*M*r + 3.0*a**2 + 3.0*r**2)*(-1.5*a**2*Sigma*np.sin(4*theta) - 1.5*a**2*dSt*np.cos(4*theta) + 1.5*a**2*dSt + r**2*Sigma*np.sin(2*theta) + 2.0*r**2*dSt*np.cos(2*theta) - 2.0*r**2*dSt)/Sigma**5, 0.]

    drijkl[2, 3, 1, 3, :] = [0., M*a**2*(r*(-6.0*a**2*np.cos(theta)**2 + 18.0*a**2 + 36.0*r**2)*Sigma + 12.0*(a**2 + r**2)*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSr)*np.sin(theta)**3*np.cos(theta)/Sigma**5, M*a**2*(a**2 + r**2)*(12.0*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (-18.0*a**2*np.sin(theta)**4 + 27.0*a**2*np.sin(theta)**2 - 9.0*a**2 - 36.0*r**2*np.sin(theta)**2 + 27.0*r**2)*Sigma)*np.sin(theta)**2/Sigma**5, 0.]

    drijkl[2, 3, 2, 3, :] = [0., M*(4*r*(3.0*a**2*np.cos(theta)**2 - r**2)*(a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2)*dSr + (2*r**2*(a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2) - r*(3.0*a**2*np.cos(theta)**2 - r**2)*(a**2*dD*np.sin(theta)**2 + 8.0*r*(a**2 + r**2)) - (3.0*a**2*np.cos(theta)**2 - r**2)*(a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2))*Sigma)*np.sin(theta)**2/Sigma**5, M*r*(4*(3.0*a**2*np.cos(theta)**2 - r**2)*(a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2)*dSt*np.sin(theta) + (-2*a**2*(3.0*a**2*np.cos(theta)**2 - r**2)*Delta*np.sin(theta)**2 + 6.0*a**2*(a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2)*np.sin(theta)**2 - 2*(3.0*a**2*np.cos(theta)**2 - r**2)*(a**2*Delta*np.sin(theta)**2 + 2.0*(a**2 + r**2)**2))*Sigma*np.cos(theta))*np.sin(theta)/Sigma**5, 0.]

    # Symmetries
    drijkl[2, 0, 1, 0, :] = -drijkl[2, 0, 0, 1, :]
    drijkl[2, 0, 2, 0, :] = -drijkl[2, 0, 0, 2, :]
    drijkl[2, 0, 3, 1, :] = -drijkl[2, 0, 1, 3, :]
    drijkl[2, 0, 3, 2, :] = -drijkl[2, 0, 2, 3, :]
    drijkl[2, 1, 3, 0, :] = -drijkl[2, 1, 0, 3, :]
    drijkl[2, 1, 2, 1, :] = -drijkl[2, 1, 1, 2, :]
    drijkl[2, 3, 1, 0, :] = -drijkl[2, 3, 0, 1, :]
    drijkl[2, 3, 2, 0, :] = -drijkl[2, 3, 0, 2, :]
    drijkl[2, 3, 3, 1, :] = -drijkl[2, 3, 1, 3, :]
    drijkl[2, 3, 3, 2, :] = -drijkl[2, 3, 2, 3, :]

    #! --------------------------------------------------------------------------#

    drijkl[3, 0, 1, 2, :] = [0., M*a*(-3*(a**2*np.sin(theta)**2 - Delta)*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*dSr - (a**2*np.sin(theta)**2 - Delta)*(a**2*np.cos(theta)**2 - 3.0*r**2)*Sigma*dD + (-6.0*r*(a**2*np.sin(theta)**2 - Delta) - (a**2*np.cos(theta)**2 - 3.0*r**2)*dD)*Delta*Sigma)/(Delta**2*Sigma**4*np.tan(theta)), M*a*(1.0*a**4*(1 - np.cos(2*theta))**2*Sigma + 2.5*a**4*Sigma*np.cos(2*theta) - 1.5*a**4*Sigma - 0.75*a**4*dSt*np.sin(2*theta) - 0.375*a**4*dSt*np.sin(4*theta) - 3.0*a**2*r**2*Sigma*np.cos(2*theta) + 4.5*a**2*r**2*dSt*np.sin(2*theta) + 1.0*a**2*Delta*Sigma*np.cos(2*theta) - 1.5*a**2*Delta*dSt*np.sin(2*theta) + 3.0*a**2*Delta*dSt/np.tan(theta) + 2.0*a**2*Delta*Sigma/(1 - np.cos(2*theta)) - 3.0*r**2*Delta*Sigma/np.sin(theta)**2 - 9.0*r**2*Delta*dSt/np.tan(theta))/(Delta*Sigma**4), 0.]

    drijkl[3, 1, 0, 1, :] = [0., M*a*(9.0*r*(3.0*a**2*np.cos(theta)**2 - r**2)*Delta*dSr + 3.0*r*(3.0*a**2*np.cos(theta)**2 - r**2)*Sigma*dD + 9.0*(-a**2*np.cos(theta)**2 + r**2)*Delta*Sigma)/(Delta**2*Sigma**4), 9.0*M*a*r*(a**2*Sigma*np.sin(2*theta) + (3.0*a**2*np.cos(theta)**2 - r**2)*dSt)/(Delta*Sigma**4), 0.]

    drijkl[3, 1, 0, 2, :] = [0., M*a*(-3*(2.0*a**2*np.sin(theta)**2 + Delta)*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*dSr - (2.0*a**2*np.sin(theta)**2 + Delta)*(a**2*np.cos(theta)**2 - 3.0*r**2)*Sigma*dD + (-6.0*r*(2.0*a**2*np.sin(theta)**2 + Delta) + (a**2*np.cos(theta)**2 - 3.0*r**2)*dD)*Delta*Sigma)/(Delta**2*Sigma**4*np.tan(theta)), M*a*(2.0*a**4*(1 - np.cos(2*theta))**2*Sigma + 5.0*a**4*Sigma*np.cos(2*theta) - 3.0*a**4*Sigma - 1.5*a**4*dSt*np.sin(2*theta) - 0.75*a**4*dSt*np.sin(4*theta) - 6.0*a**2*r**2*Sigma*np.cos(2*theta) + 9.0*a**2*r**2*dSt*np.sin(2*theta) - 1.0*a**2*Delta*Sigma*np.cos(2*theta) + 1.5*a**2*Delta*dSt*np.sin(2*theta) - 3.0*a**2*Delta*dSt/np.tan(theta) - 2.0*a**2*Delta*Sigma/(1 - np.cos(2*theta)) + 3.0*r**2*Delta*Sigma/np.sin(theta)**2 + 9.0*r**2*Delta*dSt/np.tan(theta))/(Delta*Sigma**4), 0.]

    drijkl[3, 1, 1, 3, :] = [0., M*(3*r*(3.0*a**2*np.cos(theta)**2 - r**2)*(2.0*a**2*np.sin(theta)**2 + a**2 + r**2)*Delta*dSr + r*(3.0*a**2*np.cos(theta)**2 - r**2)*(2.0*a**2*np.sin(theta)**2 + a**2 + r**2)*Sigma*dD + (6.0*a**4*np.sin(theta)**4 - 3.0*a**4*np.sin(theta)**2 - 3.0*a**4 + 15.0*a**2*r**2*np.sin(theta)**2 - 6.0*a**2*r**2 + 5.0*r**4)*Delta*Sigma)/(Delta**2*Sigma**4), M*r*(a**2*(24.0*a**2*np.sin(theta)**2 - 6.0*a**2 + 10.0*r**2)*Sigma*np.sin(theta)*np.cos(theta) + 3*(3.0*a**2*np.cos(theta)**2 - r**2)*(2.0*a**2*np.sin(theta)**2 + a**2 + r**2)*dSt)/(Delta*Sigma**4), 0.]

    drijkl[3, 1, 2, 3, :] = [0., M*a**2*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*(-2.0*M*r + 3.0*a**2 + 3.0*r**2)*Delta*dSr - (a**2*np.cos(theta)**2 - 3.0*r**2)*(-2.0*M*r + 3.0*a**2 + 3.0*r**2)*Sigma*dD + (-6.0*r*(-2.0*M*r + 3.0*a**2 + 3.0*r**2) + (-2.0*M + 6.0*r)*(a**2*np.cos(theta)**2 - 3.0*r**2))*Delta*Sigma)*np.sin(theta)*np.cos(theta)/(Delta**2*Sigma**4), M*a**2*(-3*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (4.0*a**2*np.sin(theta)**4 - 5.0*a**2*np.sin(theta)**2 + 1.0*a**2 + 6.0*r**2*np.sin(theta)**2 - 3.0*r**2)*Sigma)*(-2.0*M*r + 3.0*a**2 + 3.0*r**2)/(Delta*Sigma**4), 0.]

    drijkl[3, 2, 0, 1, :] = [0., M*a*(-3*(a**2*np.sin(theta)**2 + 2.0*Delta)*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*dSr - (a**2*np.sin(theta)**2 + 2.0*Delta)*(a**2*np.cos(theta)**2 - 3.0*r**2)*Sigma*dD + (-6.0*r*(a**2*np.sin(theta)**2 + 2.0*Delta) + 2.0*(a**2*np.cos(theta)**2 - 3.0*r**2)*dD)*Delta*Sigma)/(Delta**2*Sigma**4*np.tan(theta)), M*a*(1.0*a**4*(1 - np.cos(2*theta))**2*Sigma + 2.5*a**4*Sigma*np.cos(2*theta) - 1.5*a**4*Sigma - 0.75*a**4*dSt*np.sin(2*theta) - 0.375*a**4*dSt*np.sin(4*theta) - 3.0*a**2*r**2*Sigma*np.cos(2*theta) + 4.5*a**2*r**2*dSt*np.sin(2*theta) - 2.0*a**2*Delta*Sigma*np.cos(2*theta) + 3.0*a**2*Delta*dSt*np.sin(2*theta) - 6.0*a**2*Delta*dSt/np.tan(theta) - 4.0*a**2*Delta*Sigma/(1 - np.cos(2*theta)) + 6.0*r**2*Delta*Sigma/np.sin(theta)**2 + 18.0*r**2*Delta*dSt/np.tan(theta))/(Delta*Sigma**4), 0.]

    drijkl[3, 2, 0, 2, :] = [0., 9.0*M*a*(-r*(3.0*a**2*np.cos(theta)**2 - r**2)*dSr + (a**2*np.cos(theta)**2 - r**2)*Sigma)/Sigma**4, -9.0*M*a*r*(a**2*Sigma*np.sin(2*theta) + (3.0*a**2*np.cos(theta)**2 - r**2)*dSt)/Sigma**4, 0.]

    drijkl[3, 2, 1, 3, :] = [0., M*a**2*(-3*(a**2*np.cos(theta)**2 - 3*r**2)*(-4.0*M*r + 3.0*a**2 + 3.0*r**2)*Delta*dSr - (a**2*np.cos(theta)**2 - 3*r**2)*(-4.0*M*r + 3.0*a**2 + 3.0*r**2)*Sigma*dD + (-6*r*(-4.0*M*r + 3.0*a**2 + 3.0*r**2) + (-4.0*M + 6.0*r)*(a**2*np.cos(theta)**2 - 3*r**2))*Delta*Sigma)*np.sin(theta)*np.cos(theta)/(Delta**2*Sigma**4), M*a**2*(-3*(a**2*np.cos(theta)**2 - 3*r**2)*dSt*np.sin(theta)*np.cos(theta) + (4*a**2*np.sin(theta)**4 - 5*a**2*np.sin(theta)**2 + a**2 + 6*r**2*np.sin(theta)**2 - 3*r**2)*Sigma)*(-4.0*M*r + 3.0*a**2 + 3.0*r**2)/(Delta*Sigma**4), 0.]

    drijkl[3, 2, 2, 3, :] = [0., M*(-3*r*(3.0*a**2*np.cos(theta)**2 - r**2)*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*dSr + (-3.0*a**4*np.sin(theta)**4 - 3.0*a**4*np.sin(theta)**2 + 6.0*a**4 - 21.0*a**2*r**2*np.sin(theta)**2 + 12.0*a**2*r**2 - 10.0*r**4)*Sigma)/Sigma**4, M*r*(a**2*(12.0*a**2*np.cos(theta)**2 - 18.0*a**2 - 14.0*r**2)*Sigma*np.sin(theta)*np.cos(theta) - 3*(3.0*a**2*np.cos(theta)**2 - r**2)*(a**2*np.sin(theta)**2 + 2.0*a**2 + 2.0*r**2)*dSt)/Sigma**4, 0.] 

    drijkl[3, 3, 0, 3, :] = [0., M**2*a*r*(-8.0*r*(3.0*a**2*np.cos(theta)**2 - r**2)*dSr + 4.0*(3.0*a**2*np.cos(theta)**2 - 2.0*r**2)*Sigma)*np.sin(theta)**2/Sigma**5, M**2*a*r**2*(3.0*a**2*Sigma*np.sin(4*theta) + 3.0*a**2*dSt*np.cos(4*theta) - 3.0*a**2*dSt - 2.0*r**2*Sigma*np.sin(2*theta) - 4.0*r**2*dSt*np.cos(2*theta) + 4.0*r**2*dSt)/Sigma**5, 0.]

    drijkl[3, 3, 1, 2, :] = [0., M**2*a**2*(6.0*r*(a**2*np.cos(theta)**2 - 3.0*r**2)*Delta*dSr + 2.0*r*(a**2*np.cos(theta)**2 - 3.0*r**2)*Sigma*dD + (-2.0*a**2*np.cos(theta)**2 + 18.0*r**2)*Delta*Sigma)*np.sin(theta)*np.cos(theta)/(Delta**2*Sigma**4), M**2*a**2*r*(6.0*(a**2*np.cos(theta)**2 - 3.0*r**2)*dSt*np.sin(theta)*np.cos(theta) + (-8.0*a**2*np.sin(theta)**4 + 10.0*a**2*np.sin(theta)**2 - 2.0*a**2 - 12.0*r**2*np.sin(theta)**2 + 6.0*r**2)*Sigma)/(Delta*Sigma**4), 0.]

    # Symmetries
    drijkl[3, 0, 2, 1, :] = -drijkl[3, 0, 1, 2, :]
    drijkl[3, 1, 1, 0, :] = -drijkl[3, 1, 0, 1, :]
    drijkl[3, 1, 2, 0, :] = -drijkl[3, 1, 0, 2, :]
    drijkl[3, 1, 3, 1, :] = -drijkl[3, 1, 1, 3, :]
    drijkl[3, 1, 3, 2, :] = -drijkl[3, 1, 2, 3, :]
    drijkl[3, 2, 1, 0, :] = -drijkl[3, 2, 0, 1, :]
    drijkl[3, 2, 2, 0, :] = -drijkl[3, 2, 0, 2, :]
    drijkl[3, 2, 3, 1, :] = -drijkl[3, 2, 1, 3, :]
    drijkl[3, 2, 3, 2, :] = -drijkl[3, 2, 2, 3, :]
    drijkl[3, 3, 3, 0, :] = -drijkl[3, 3, 0, 3, :]
    drijkl[3, 3, 2, 1, :] = -drijkl[3, 3, 1, 2, :]

    #!---------------------------------------------------------------------#

    part1 = a**2 + 2 * r * (-2 * M + r) + a**2 * sme.cos(2 * theta)
    part2 = 3 * a**2 - 2 * r**2 + 3 * a**2 * sme.cos(2 * theta)
    part3 = (a**2 + 2 * r**2 + a**2 * sme.cos(2 * theta)) ** 4
    # Calculating Rtensor elements

    drijkl[3, 0, 0, 3, :] = [0., M*(-8*r**2*(3*a**2*np.cos(theta)**2 - r**2)*(-2*M*r + a**2*np.cos(theta)**2 + r**2) + (a**2*np.cos(theta)**2 + r**2)*(-12*M*a**2*r*np.cos(theta)**2 + 8*M*r**3 + 3*a**4*(1 - np.cos(theta)**2)**2 + 6*a**4*np.cos(theta)**2 - 3*a**4 + 6*a**2*r**2*np.cos(theta)**2 - 5*r**4))/(a**2*np.cos(theta)**2 + r**2)**5, (1/2)*M*a**2*r*(-36*M*a**2*r*np.cos(theta)**2 + 28*M*r**3 + 12*a**4*(1 - np.cos(theta)**2)**2 + 24*a**4*np.cos(theta)**2 - 12*a**4 - 12*r**4)*np.sin(2*theta)/(a**2*np.cos(theta)**2 + r**2)**5, 0.]
    drijkl[3, 0, 3, 0, :] = -drijkl[3, 0, 0, 3, :]

    # return drijkl
    if config == "ullll":
        return drijkl + np.zeros((4, 4, 4, 4, 4))

    elif config == "lllll":
        gk = cov_metric_tensor(r=r, theta=theta, a=a, M=M)
        return np.einsum("ij,jklmp->iklmp", gk, drijkl) + np.zeros((4, 4, 4, 4, 4))

    # elif config=="lluu":
    #     #!Config: lluu
    #     gkinv = cot_metric_tensor(r=r, theta=theta, a=a, M=M)
    #     gk = cov_metric_tensor(r=r, theta=theta, a=a, M=M)
    #     rllll = np.einsum("ij,jklm->iklm", gk, drijkl)

    #   , :  return np.einsum("kjlm,la,mb->kjab", rllll, gkinv, gkinv)

    return drijkl

In [5]:
M, r, theta, a = 2.3, 12.52, np.pi / 7.0, 2.3

In [6]:
np.sin(theta), np.cos(theta)

(0.4338837391175581, 0.9009688679024191)

In [7]:
print(DRijkl(r, theta, a, M)[3, 0, :, :, :])

[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  1.08599214e-04 -9.49324522e-05  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00 -3.68205045e-04 -3.04919754e-03  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  3.68205045e-04  3.04919754e-03  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00 -1.08599214e-04  9.49324522e-05  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.0000

In [16]:
i_, j_, k_, l_ = 0, 0, 0, 3

In [17]:
r_, theta_, a_, M_ = sme.symbols("r theta a M", real=True)
Delta = sme.Function("Delta", real=True)(r_)
Sigma = sme.Function("Sigma", real=True)(r_, theta_)
dSr_ = sme.Function("dSr", real=True)(r_)
dSt_ = sme.Function("dSt", real=True)(theta_)
dDelta = sme.Function("dD", real=True)(r_)
denom = sme.Function("denom", real=True)(r_, theta_)
ddenommr = sme.Function("ddmr", real=True)(r_, theta_)
ddenommt = sme.Function("ddmt", real=True)(r_, theta_)

In [18]:
r0003r = sme.Derivative(
    Skerr_riemann_tensor(r_, theta_, a_, Delta, Sigma, M_)[i_, j_, k_, l_], r_
).simplify()


r0003t = sme.Derivative(
    Skerr_riemann_tensor(r_, theta_, a_, Delta, Sigma, M_)[i_, j_, k_, l_], theta_
).simplify()

In [19]:
sr0003r = r0003r.subs(smp.Derivative(Sigma, r_), dSr_).subs(
    smp.Derivative(Delta, r_), dDelta
)
sr0003t = r0003t.subs(smp.Derivative(Sigma, theta_), dSt_)

In [20]:
matr0003 = smp.Matrix([0.0, sr0003r, sr0003t, 0.0])

In [49]:
y= smp.IndexedBase('rijkl',shape=(4,4,4,4))
Dy = smp.IndexedBase("drijkl", shape=(4, 4, 4, 4, 4))
id = smp.Idx("i", 4)

In [60]:
id.label

i

In [59]:
Dy[0, 0, 0, 3, id]

drijkl[0, 0, 0, 3, i]

In [62]:
y[0, 0, 0, 3][id]

TypeError: 'Indexed' object is not subscriptable

In [61]:
smp.Eq(y[0, 0, 0, 3][id], sr0003r)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (634078282.py, line 1)

In [48]:
sr0003r

M**2*a*r*sin(theta)**2*(4.0*Sigma(r, theta)*(-3.0*a**2*cos(theta)**2 + 2.0*r**2) + 8.0*r*dSr(r)*(3.0*a**2*cos(theta)**2 - r**2))/Sigma(r, theta)**5

In [46]:
print(smp.ccode(sr0003r, assign_to=y[0, 0, 0, 3, 0]))

AttributeError: 'Integer' object has no attribute 'label'

In [23]:
print(pycode(matr0003))

  # Not supported in Python:
  # Sigma
  # dSr
  # dSt
ImmutableDenseMatrix([[0], [M**2*a*r*(8.0*r*(3.0*a**2*math.cos(theta)**2 - r**2)*dSr(r) + 4.0*(-3.0*a**2*math.cos(theta)**2 + 2.0*r**2)*Sigma(r, theta))*math.sin(theta)**2/Sigma(r, theta)**5], [M**2*a*r**2*(-3.0*a**2*Sigma(r, theta)*math.sin(4*theta) - 3.0*a**2*dSt(theta)*math.cos(4*theta) + 3.0*a**2*dSt(theta) + 2.0*r**2*Sigma(r, theta)*math.sin(2*theta) + 4.0*r**2*dSt(theta)*math.cos(2*theta) - 4.0*r**2*dSt(theta))/Sigma(r, theta)**5], [0]])


In [11]:
def Dkerr_christoffel(r, theta, a, M=1.0):
    """
    Function to give the christoffel symbols for kerr metric.
    The christoffel symbols are given as \Gamma ^i _{jk}

    From Reference Paper, Appendix
    Config: ull
    """

    dcs = np.zeros((4, 4, 4, 4), dtype=type(r))

    # Definitions
    Delta=  a**2 - 2 * M * r + r**2
    Sigma =  r**2 + a**2 * np.cos(theta) ** 2
    dSt= -a**2*np.sin(2*theta)
    dSr=  2*r
    dD=  2*(r-M)

    dcs[3, 0, 1, [[1,2]]] = [M*a*((4*r - dSr)*Delta*Sigma - 2*(2*r**2 - Sigma)*Delta*dSr - (2*r**2 - Sigma)*Sigma*dD)/(Delta**2*Sigma**3), M*a*(-4*r**2 + Sigma)*dSt/(Delta*Sigma**3)]
    
    dcs[0, 0, 1, [[1,2]]] = [M*(2*r*(a**2*np.sin(theta)**2 + 2*r**2)*Delta*Sigma + 2*(a**2 + r**2)*(a**2*np.cos(theta)**2 - r**2)*Delta*dSr + (a**2 + r**2)*(a**2*np.cos(theta)**2 - r**2)*Sigma*dD)/(Delta**2*Sigma**3), 2*M*(a**2 + r**2)*((1/2)*a**2*Sigma*np.sin(2*theta) + (a**2*np.cos(theta)**2 - r**2)*dSt)/(Delta*Sigma**3)]

    dcs[3, 0, 2, [[1,2]]] = [2*M*a*(2*r*dSr - Sigma)/(Sigma**3*np.tan(theta)), 2*M*a*r*(Sigma + dSt*np.sin(2*theta))/(Sigma**3*np.sin(theta)**2)]
    
    dcs[0, 0, 2, [[1,2]]] = [M*a**2*(2*r*dSr - Sigma)*np.sin(2*theta)/Sigma**3, 2*M*a**2*r*(-Sigma*np.cos(2*theta) + dSt*np.sin(2*theta))/Sigma**3]

    dcs[0, 1, 3, [[1,2]]] = [M*a*(2*(2*r**2*(a**2 + r**2) - (a**2 - r**2)*Sigma)*Delta*dSr + (2*r**2*(a**2 + r**2) - (a**2 - r**2)*Sigma)*Sigma*dD - (4*r**3 + 4*r*(a**2 + r**2) + 2*r*Sigma - (a**2 - r**2)*dSr)*Delta*Sigma)*np.sin(theta)**2/(Delta**2*Sigma**3), M*a*(2*(2*r**2*(a**2 + r**2) - (a**2 - r**2)*Sigma)*dSt*np.sin(theta) + ((a**2 - r**2)*dSt*np.sin(theta) + (-4*r**2*(a**2 + r**2) + 2*(a**2 - r**2)*Sigma)*np.cos(theta))*Sigma)*np.sin(theta)/(Delta*Sigma**3)]

    dcs[3, 1, 3, [[1,2]]] = [(2*(M*a**2*(2*r**2 - Sigma)*np.sin(theta)**2 + r*(2*M*r - Sigma)*Sigma)*Delta*dSr + (M*a**2*(2*r**2 - Sigma)*np.sin(theta)**2 + r*(2*M*r - Sigma)*Sigma)*Sigma*dD - (M*a**2*(4*r - dSr)*np.sin(theta)**2 + r*(2*M - dSr)*Sigma + r*(2*M*r - Sigma)*dSr + (2*M*r - Sigma)*Sigma)*Delta*Sigma)/(Delta**2*Sigma**3), M*(-2*a**2*r**2*Sigma*np.sin(2*theta) + 4*a**2*r**2*dSt*np.sin(theta)**2 + a**2*Sigma**2*np.sin(2*theta) - a**2*Sigma*dSt*np.sin(theta)**2 + 2*r**2*Sigma*dSt)/(Delta*Sigma**3)]

    dcs[0, 2, 3, [[1,2]]] = [2*M*a**3*(-2*r*dSr + Sigma)*np.sin(theta)**3*np.cos(theta)/Sigma**3, 2*M*a**3*r*(Sigma*np.sin(3*theta) - dSt*np.sin(theta)*np.sin(2*theta))*np.sin(theta)/Sigma**3]

    dcs[3, 2, 3, [[1,2]]] = [M*a**2*(-2*r*dSr + Sigma)*np.sin(2*theta)/Sigma**3, 2*M*a**2*r*np.cos(2*theta)/Sigma**2 - 2*M*a**2*r*dSt*np.sin(2*theta)/Sigma**3 + 2/(np.cos(2*theta) - 1)]

    dcs[1, 0, 0, [[1,2]]] = [M*(-3*(2*r**2 - Sigma)*Delta*dSr + ((4*r - dSr)*Delta + (2*r**2 - Sigma)*dD)*Sigma)/Sigma**4, 2*M*(-3*r**2 + Sigma)*Delta*dSt/Sigma**4]

    dcs[1, 0, 3, [[1,2]]] = [M*a*(3*(2*r**2 - Sigma)*Delta*dSr - ((4*r - dSr)*Delta + (2*r**2 - Sigma)*dD)*Sigma)*np.sin(theta)**2/Sigma**4, M*a*(3*(2*r**2 - Sigma)*dSt*np.sin(theta) + ((-4*r**2 + 2*Sigma)*np.cos(theta) + dSt*np.sin(theta))*Sigma)*Delta*np.sin(theta)/Sigma**4]

    dcs[2, 0, 0, [[1,2]]] = [M*a**2*(3*r*dSr - Sigma)*np.sin(2*theta)/Sigma**4, M*a**2*r*(-2*Sigma*np.cos(2*theta) + 3*dSt*np.sin(2*theta))/Sigma**4]

    dcs[2, 0, 3, [[1,2]]] = [(1/2)*M*a*(-6.0*r*(a**2 + r**2)*dSr + (2.0*a**2 + 6.0*r**2)*Sigma)*np.sin(2*theta)/Sigma**4, M*a*r*(a**2 + r**2)*(2.0*Sigma*np.cos(2*theta) - 3.0*dSt*np.sin(2*theta))/Sigma**4]

    dcs[1, 1, 1, [[1,2]]] = [-M*dD/Delta**2 - r*dSr/Sigma**2 + r*dD/Delta**2 + 1/Sigma - 1/Delta, -r*dSt/Sigma**2]

    dcs[1, 2, 2, [[1,2]]] = [(r*Delta*dSr - (r*dD + Delta)*Sigma)/Sigma**2, r*Delta*dSt/Sigma**2]
    
    dcs[2, 1, 2, [[1,2]]] = [(-r*dSr + Sigma)/Sigma**2, -r*dSt/Sigma**2]

    dcs[1, 1, 2, [[1,2]]] = dcs[2, 2, 2, [[1,2]]] = [(1/2)*a**2*dSr*np.sin(2*theta)/Sigma**2, a**2*(-Sigma*np.cos(2*theta) + (1/2)*dSt*np.sin(2*theta))/Sigma**2]
    
    dcs[2, 1, 1, [[1,2]]] = [(1/2)*a**2*(-Delta*dSr - Sigma*dD)*np.sin(2*theta)/(Delta**2*Sigma**2), a**2*(Sigma*np.cos(2*theta) - 1/2*dSt*np.sin(2*theta))/(Delta*Sigma**2)]

    dcs[1, 3, 3, [[1,2]]] = [(((M*a**2*(2*r**2 - Sigma)*np.sin(theta)**2 - r*Sigma**2)*dD - (-M*a**2*(4*r - dSr)*np.sin(theta)**2 + 2*r*Sigma*dSr + Sigma**2)*Delta)*Sigma - 3*(M*a**2*(2*r**2 - Sigma)*np.sin(theta)**2 - r*Sigma**2)*Delta*dSr)*np.sin(theta)**2/Sigma**4, (-3/2*M*a**2*r**2*(1 - np.cos(2*theta))**2*dSt + 2*M*a**2*r**2*Sigma*np.sin(2*theta) - M*a**2*r**2*Sigma*np.sin(4*theta) + (1/2)*M*a**2*(1 - np.cos(2*theta))**2*Sigma*dSt - M*a**2*Sigma**2*np.sin(2*theta) + (1/2)*M*a**2*Sigma**2*np.sin(4*theta) - r*Sigma**3*np.sin(2*theta) - 1/2*r*Sigma**2*dSt*np.cos(2*theta) + (1/2)*r*Sigma**2*dSt)*Delta/Sigma**4]

    dcs[2, 3, 3, [[1,2]]] = [(1/2)*(3*(2*M*r*(a**2 + r**2)**2 + Delta*Sigma**2)*dSr - (8*M*r**2*(a**2 + r**2) + 2*M*(a**2 + r**2)**2 + 2*Delta*Sigma*dSr + Sigma**2*dD)*Sigma)*np.sin(2*theta)/Sigma**4, -2*M*r*(a**2 + r**2)**2*np.cos(2*theta)/Sigma**3 + 3*M*r*(a**2 + r**2)**2*dSt*np.sin(2*theta)/Sigma**4 - Delta*np.cos(2*theta)/Sigma + (1/2)*Delta*dSt*np.sin(2*theta)/Sigma**2]

    dcs[0, 1, 0, [[1,2]]] = dcs[0, 0, 1, [[1,2]]]
    dcs[0, 2, 0, [[1,2]]] = dcs[0, 0, 2, [[1,2]]]
    dcs[0, 3, 1, [[1,2]]] = dcs[0, 1, 3, [[1,2]]]
    dcs[0, 3, 2, [[1,2]]] = dcs[0, 2, 3, [[1,2]]]

    dcs[1, 3, 0, [[1,2]]] = dcs[1, 0, 3, [[1,2]]]
    dcs[1, 2, 1, [[1,2]]] = dcs[1, 1, 2, [[1,2]]]

    dcs[2, 3, 0, [[1,2]]] = dcs[2, 0, 3, [[1,2]]]
    dcs[2, 2, 1, [[1,2]]] = dcs[2, 1, 2, [[1,2]]]

    dcs[3, 1, 0, [[1,2]]] = dcs[3, 0, 1, [[1,2]]]
    dcs[3, 2, 0, [[1,2]]] = dcs[3, 0, 2, [[1,2]]]
    dcs[3, 3, 1, [[1,2]]] = dcs[3, 1, 3, [[1,2]]]
    dcs[3, 3, 2, [[1,2]]] = dcs[3, 2, 3, [[1,2]]]

    # return symmetrize(arr=dcs)+np.zer, [[1,2]]os((4,4,4))
    return dcs + np.zeros((4, 4, 4, 4))
    # return dcs, [[1,2]]

In [12]:
def Skerr_christoffel(r, theta, a, Delta, Sigma, M=1.0):
    """
    Function to give the christoffel symbols for kerr metric.
    The christoffel symbols are given as \Gamma ^i _{jk}

    From Reference Paper, Appendix
    Config: ull
    """

    cs = np.zeros((4, 4, 4), dtype=type(r))

    # Definitions
    # Delta = a**2 - 2 * M * r + r**2
    # Sigma = r**2 + a**2 * sme.cos(theta) ** 2

    cs[3, 0, 1] = M * (2 * r**2 - Sigma) / (Delta * Sigma**2) * a
    cs[0, 0, 1] = (
        M * (r**2 + a**2) * (r**2 - a**2 * sme.cos(theta) ** 2) / (Sigma**2 * Delta)
    )

    cs[3, 0, 2] = -2 * M * a * r * (sme.cos(theta) / sme.sin(theta)) / (Sigma**2)
    cs[0, 0, 2] = -2 * M * a**2 * r * sme.sin(theta) * sme.cos(theta) / Sigma**2

    cs[0, 1, 3] = (
        -M
        * a
        * (2 * r**2 * (r**2 + a**2) + Sigma * (r**2 - a**2))
        * sme.sin(theta) ** 2
        / (Delta * Sigma**2)
    )

    cs[3, 1, 3] = (
        r * Sigma * (Sigma - 2 * M * r)
        - M * a**2 * (2 * r**2 - Sigma) * sme.sin(theta) ** 2
    ) / (Delta * Sigma**2)

    cs[0, 2, 3] = M * a**3 * r * sme.sin(theta) ** 2 * sme.sin(2 * theta) / Sigma**2

    cs[3, 2, 3] = (
        (sme.cos(theta) / sme.sin(theta))
        * (Sigma**2 + 2 * M * a**2 * r * sme.sin(theta) ** 2)
        / Sigma**2
    )

    cs[1, 0, 0] = M * Delta * (2 * r**2 - Sigma) / Sigma**3

    cs[1, 0, 3] = -cs[1, 0, 0] * a * sme.sin(theta) ** 2

    cs[2, 0, 0] = -M * a * r * sme.sin(2 * theta) / Sigma**3 * a
    cs[2, 0, 3] = (
        2.0 * M * r * a * (r**2 + a**2) * sme.sin(theta) * sme.cos(theta) / Sigma**3
    )

    cs[1, 1, 1] = r / Sigma + (M - r) / Delta

    cs[1, 2, 2] = -r * Delta / Sigma
    cs[2, 1, 2] = -cs[1, 2, 2] / Delta

    cs[1, 1, 2] = cs[2, 2, 2] = -(a**2) * sme.sin(2 * theta) / (2 * Sigma)
    cs[2, 1, 1] = -cs[1, 1, 2] / Delta

    cs[1, 3, 3] = (
        -Delta
        * (r * Sigma**2 - M * a**2 * (2 * r**2 - Sigma) * sme.sin(theta) ** 2)
        * sme.sin(theta) ** 2
        / Sigma**3
    )

    cs[2, 3, 3] = (
        -(Delta * Sigma**2 + 2 * M * r * (r**2 + a**2) ** 2)
        * sme.sin(2 * theta)
        / (2 * Sigma**3)
    )

    cs[0, 1, 0] = cs[0, 0, 1]
    cs[0, 2, 0] = cs[0, 0, 2]
    cs[0, 3, 1] = cs[0, 1, 3]
    cs[0, 3, 2] = cs[0, 2, 3]

    cs[1, 3, 0] = cs[1, 0, 3]
    cs[1, 2, 1] = cs[1, 1, 2]

    cs[2, 3, 0] = cs[2, 0, 3]
    cs[2, 2, 1] = cs[2, 1, 2]

    cs[3, 1, 0] = cs[3, 0, 1]
    cs[3, 2, 0] = cs[3, 0, 2]
    cs[3, 3, 1] = cs[3, 1, 3]
    cs[3, 3, 2] = cs[3, 2, 3]

    # return symmetrize(arr=cs)+np.zeros((4,4,4))
    return cs + np.zeros((4, 4, 4))
    # return cs

In [13]:
M, r, theta, a = 2.3, 43.52, np.pi / 11.0, 0.24

In [14]:
i_, j_, k_ = 2, 3, 3

In [15]:
r_, theta_, a_, M_ = sme.symbols("r theta a M", real=True)
Delta = sme.Function("Delta", real=True)(r_)
Sigma = sme.Function("Sigma", real=True)(r_, theta_)
dSr_ = sme.Function("dSr", real=True)(r_)
dSt_ = sme.Function("dSt", real=True)(theta_)
dDelta = sme.Function("dD", real=True)(r_)

In [16]:
r0003r = sme.Derivative(
    Skerr_christoffel(r_, theta_, a_, Delta, Sigma, M_)[i_, j_, k_], r_
).simplify()


r0003t = sme.Derivative(
    Skerr_christoffel(r_, theta_, a_, Delta, Sigma, M_)[i_, j_, k_], theta_
).simplify()

In [17]:
sr0003r = r0003r.subs(smp.Derivative(Sigma, r_), dSr_).subs(
    smp.Derivative(Delta, r_), dDelta
)
sr0003t = r0003t.subs(smp.Derivative(Sigma, theta_), dSt_)

In [18]:
matr0003 = smp.Matrix([sr0003r, sr0003t])

In [19]:
rhsmatr0003 = smp.MatrixSymbol("R0003", 1, 3)

In [20]:
print(i_, j_, k_)

2 3 3


In [21]:
print(pycode(matr0003))

  # Not supported in Python:
  # Delta
  # Sigma
  # dD
  # dSr
  # dSt
ImmutableDenseMatrix([[(1/2)*(3*(2*M*r*(a**2 + r**2)**2 + Delta(r)*Sigma(r, theta)**2)*dSr(r) - (8*M*r**2*(a**2 + r**2) + 2*M*(a**2 + r**2)**2 + 2*Delta(r)*Sigma(r, theta)*dSr(r) + Sigma(r, theta)**2*dD(r))*Sigma(r, theta))*math.sin(2*theta)/Sigma(r, theta)**4], [-2*M*r*(a**2 + r**2)**2*math.cos(2*theta)/Sigma(r, theta)**3 + 3*M*r*(a**2 + r**2)**2*dSt(theta)*math.sin(2*theta)/Sigma(r, theta)**4 - Delta(r)*math.cos(2*theta)/Sigma(r, theta) + (1/2)*Delta(r)*dSt(theta)*math.sin(2*theta)/Sigma(r, theta)**2]])


In [22]:
def Dcov_metric_tensor(r, theta, a, M=1.0):
    """
    Define the metric tensor function.

    Parameters:
        a (float): Parameter 'a' in the metric.
        r (float): Parameter 'r' in the metric.
        theta (float): Parameter 'theta' in the metric.

    Returns:
        np.ndarray: The metric tensor at the given values of a, r, and theta.
        Configuration: ll
    """
    #! Correction Added Mass term in the symbols
    dg = np.zeros((4, 4, 4), dtype=type(r))

    # Definitions
    Delta = a**2 - 2 * M * r + r**2
    Sigma = r**2 + a**2 * np.cos(theta) ** 2
    dSt = -(a**2) * np.sin(2 * theta)
    dSr = 2 * r
    dD = 2 * (r - M)

    dg[0, 0, [[1, 2]]] = [
        2.0 * M * (-r * dSr + Sigma) / Sigma**2,
        -2.0 * M * r * dSt / Sigma**2,
    ]

    dg[1, 1, [[1, 2]]] = [(Delta * dSr - Sigma * dD) / Delta**2, dSt / Delta]

    dg[2, 2, [[1, 2]]] = [dSr, dSt]

    dg[3, 3, [[1, 2]]] = [
        (
            (a**2 * Delta * np.sin(theta) ** 2 - (a**2 + r**2) ** 2) * dSr
            + (-(a**2) * dD * np.sin(theta) ** 2 + 4 * r * (a**2 + r**2)) * Sigma
        )
        * np.sin(theta) ** 2
        / Sigma**2,
        (
            2
            * (-2 * a**2 * Delta * np.sin(theta) ** 2 + (a**2 + r**2) ** 2)
            * Sigma
            * np.cos(theta)
            + (a**2 * Delta * np.sin(theta) ** 2 - (a**2 + r**2) ** 2)
            * dSt
            * np.sin(theta)
        )
        * np.sin(theta)
        / Sigma**2,
    ]

    dg[0, 3, [[1, 2]]] = [
        2.0 * M * a * (r * dSr - Sigma) * np.sin(theta) ** 2 / Sigma**2,
        M
        * a
        * r
        * (-2.0 * Sigma * np.sin(2 * theta) - 1.0 * dSt * np.cos(2 * theta) + 1.0 * dSt)
        / Sigma**2,
    ]

    dg[3, 0, [[1, 2]]] = dg[0, 3, [[1, 2]]]

    # return dg.asty, [[1,2]]pe(float)
    return dg

In [23]:
def Scov_metric_tensor(r, theta, a, Delta, Sigma, M=1.0):
    """
    Define the metric tensor function.

    Parameters:
        a (float): Parameter 'a' in the metric.
        r (float): Parameter 'r' in the metric.
        theta (float): Parameter 'theta' in the metric.

    Returns:
        np.ndarray: The metric tensor at the given values of a, r, and theta.
        Configuration: ll
    """
    #! Correction Added Mass term in the symbols
    g = np.zeros((4, 4), dtype=type(r))

    # Delta = a**2 - 2 * M * r + r**2
    # Sigma = r**2 + a**2 * np.cos(theta) ** 2

    g[0, 0] = -(1.0 - 2.0 * M * r / Sigma)
    g[1, 1] = Sigma / Delta
    g[2, 2] = Sigma
    g[3, 3] = (
        sme.sin(theta) ** 2
        * ((r**2 + a**2) ** 2 - Delta * a**2 * sme.sin(theta) ** 2)
        / Sigma
    )
    g[0, 3] = -2.0 * a * M * r * sme.sin(theta) ** 2 / Sigma
    g[3, 0] = g[0, 3]

    # return g.astype(float)
    return g

In [24]:
i_, j_ = 0, 3

In [25]:
r_, theta_, a_, M_ = sme.symbols("r theta a M", real=True)
Delta = sme.Function("Delta", real=True)(r_)
Sigma = sme.Function("Sigma", real=True)(r_, theta_)
dSr_ = sme.Function("dSr", real=True)(r_)
dSt_ = sme.Function("dSt", real=True)(theta_)
dDelta = sme.Function("dD", real=True)(r_)

In [26]:
r0003r = sme.Derivative(
    Scov_metric_tensor(r_, theta_, a_, Delta, Sigma, M_)[i_, j_], r_
).simplify()


r0003t = sme.Derivative(
    Scov_metric_tensor(r_, theta_, a_, Delta, Sigma, M_)[i_, j_], theta_
).simplify()

In [27]:
sr0003r = r0003r.subs(smp.Derivative(Sigma, r_), dSr_).subs(
    smp.Derivative(Delta, r_), dDelta
)
sr0003t = r0003t.subs(smp.Derivative(Sigma, theta_), dSt_)

In [28]:
matr0003 = smp.Matrix([sr0003r, sr0003t])

In [29]:
print(i_, j_)

0 3


In [30]:
print(pycode(matr0003))

  # Not supported in Python:
  # Sigma
  # dSr
  # dSt
ImmutableDenseMatrix([[2.0*M*a*(r*dSr(r) - Sigma(r, theta))*math.sin(theta)**2/Sigma(r, theta)**2], [M*a*r*(-2.0*Sigma(r, theta)*math.sin(2*theta) - 1.0*dSt(theta)*math.cos(2*theta) + 1.0*dSt(theta))/Sigma(r, theta)**2]])


In [31]:
def Dcot_metric_tensor(r, theta, a, M=1.0):
    """
    Define the metric tensor function.

    Parameters:
        a (float): Parameter 'a' in the metric.
        r (float): Parameter 'r' in the metric.
        theta (float): Parameter 'theta' in the metric.

    Returns:
        np.ndarray: The metric tensor at the given values of a, r, and theta.
        Configuration: uu
    """
    # Definitions
    Delta = a**2 - 2 * M * r + r**2
    Sigma = r**2 + a**2 * np.cos(theta) ** 2
    dSt = -(a**2) * np.sin(2 * theta)
    dSr = 2 * r
    dD = 2 * (r - M)

    denom = Delta * np.sin(theta) ** 2
    ddmr = dD * np.sin(theta) ** 2
    ddmt = Delta * np.sin(2 * theta)

    dg = np.zeros((4, 4, 4), dtype=type(r))

    dg[0, 0, [[1, 2]]] = [
        (
            -(a**2 * Delta * np.sin(theta) ** 2 - (a**2 + r**2) ** 2) * Sigma * ddmr
            - (a**2 * Delta * np.sin(theta) ** 2 - (a**2 + r**2) ** 2) * dSr * denom
            + (a**2 * dD * np.sin(theta) ** 2 - 4 * r * (a**2 + r**2)) * Sigma * denom
        )
        * np.sin(theta) ** 2
        / (Sigma**2 * denom**2),
        (
            -(a**2 * Delta * np.sin(theta) ** 2 - (a**2 + r**2) ** 2)
            * Sigma
            * ddmt
            * np.sin(theta)
            - (a**2 * Delta * np.sin(theta) ** 2 - (a**2 + r**2) ** 2)
            * dSt
            * denom
            * np.sin(theta)
            + 2
            * (2 * a**2 * Delta * np.sin(theta) ** 2 - (a**2 + r**2) ** 2)
            * Sigma
            * denom
            * np.cos(theta)
        )
        * np.sin(theta)
        / (Sigma**2 * denom**2),
    ]

    dg[1, 1, [[1, 2]]] = [
        (-Delta * dSr + Sigma * dD) / Sigma**2,
        -Delta * dSt / Sigma**2,
    ]

    dg[2, 2, [[1, 2]]] = [-1.0 * dSr / Sigma**2, -1.0 * dSt / Sigma**2]

    dg[3, 3, [[1, 2]]] = [
        (
            (a**2 * np.sin(theta) ** 2 - Delta) * Sigma * ddmr
            + (a**2 * np.sin(theta) ** 2 - Delta) * dSr * denom
            + Sigma * dD * denom
        )
        / (Sigma**2 * denom**2),
        (
            -(a**2) * Sigma * denom * np.sin(2 * theta)
            + (a**2 * np.sin(theta) ** 2 - Delta) * Sigma * ddmt
            + (a**2 * np.sin(theta) ** 2 - Delta) * dSt * denom
        )
        / (Sigma**2 * denom**2),
    ]

    dg[0, 3, [[1, 2]]] = [
        2.0
        * M
        * a
        * (r * Sigma * ddmr + r * dSr * denom - Sigma * denom)
        * np.sin(theta) ** 2
        / (Sigma**2 * denom**2),
        M
        * a
        * r
        * (
            -1.0 * Sigma * ddmt * np.cos(2 * theta)
            + 1.0 * Sigma * ddmt
            - 2.0 * Sigma * denom * np.sin(2 * theta)
            - 1.0 * dSt * denom * np.cos(2 * theta)
            + 1.0 * dSt * denom
        )
        / (Sigma**2 * denom**2),
    ]

    dg[3, 0, [[1, 2]]] = dg[0, 3, [[1, 2]]]

    return dg  # return dg, [[1,2]]

In [32]:
def Scot_metric_tensor(r, theta, a, Delta, Sigma, denom, M=1.0):
    """
    Define the metric tensor function.

    Parameters:
        a (float): Parameter 'a' in the metric.
        r (float): Parameter 'r' in the metric.
        theta (float): Parameter 'theta' in the metric.

    Returns:
        np.ndarray: The metric tensor at the given values of a, r, and theta.
        Configuration: uu
    """
    # Delta = a**2 - 2 * M * r + r**2
    # Sigma = r**2 + a**2 * np.cos(theta) ** 2

    # denom = Delta * sme.sin(theta) ** 2

    g = np.zeros((4, 4), dtype=type(r))
    g[0, 0] = (
        -(
            sme.sin(theta) ** 2
            * ((r**2 + a**2) ** 2 - Delta * a**2 * sme.sin(theta) ** 2)
            / Sigma
        )
        / denom
    )

    g[1, 1] = Delta / Sigma

    g[2, 2] = 1.0 / Sigma

    # g[3, 3] = -(-(1.0 - 2.0 * r / Sigma)) / denom
    #! Corrected the g[3,3] term below
    g[3, 3] = (Delta - a**2 * sme.sin(theta) ** 2) / (denom * Sigma)

    g[0, 3] = (-2.0 * a * M * r * sme.sin(theta) ** 2 / Sigma) / denom

    g[3, 0] = g[0, 3]

    return g
    # return g

In [33]:
i_, j_ = 0, 3

In [34]:
r_, theta_, a_, M_ = sme.symbols("r theta a M", real=True)
Delta = sme.Function("Delta", real=True)(r_)
Sigma = sme.Function("Sigma", real=True)(r_, theta_)
dSr_ = sme.Function("dSr", real=True)(r_)
dSt_ = sme.Function("dSt", real=True)(theta_)
dDelta = sme.Function("dD", real=True)(r_)
denom = sme.Function("denom", real=True)(r_, theta_)
ddenommr = sme.Function("ddmr", real=True)(r_, theta_)
ddenommt = sme.Function("ddmt", real=True)(r_, theta_)

In [35]:
r0003r = sme.Derivative(
    Scot_metric_tensor(r_, theta_, a_, Delta, Sigma, denom, M_)[i_, j_], r_
).simplify()


r0003t = sme.Derivative(
    Scot_metric_tensor(r_, theta_, a_, Delta, Sigma, denom, M_)[i_, j_], theta_
).simplify()

In [36]:
sr0003r = (
    r0003r.subs(smp.Derivative(Sigma, r_), dSr_)
    .subs(smp.Derivative(Delta, r_), dDelta)
    .subs(smp.Derivative(denom, r_), ddenommr)
    .subs(smp.Derivative(denom, theta_), ddenommt)
)
sr0003t = (
    r0003t.subs(smp.Derivative(Sigma, theta_), dSt_)
    .subs(smp.Derivative(denom, r_), ddenommr)
    .subs(smp.Derivative(denom, theta_), ddenommt)
)

In [37]:
matr0003 = smp.Matrix([sr0003r, sr0003t])

In [38]:
i_, j_

(0, 3)

In [39]:
print(pycode(matr0003))

  # Not supported in Python:
  # Sigma
  # dSr
  # dSt
  # ddmr
  # ddmt
  # denom
ImmutableDenseMatrix([[2.0*M*a*(r*Sigma(r, theta)*ddmr(r, theta) + r*dSr(r)*denom(r, theta) - Sigma(r, theta)*denom(r, theta))*math.sin(theta)**2/(Sigma(r, theta)**2*denom(r, theta)**2)], [M*a*r*(-1.0*Sigma(r, theta)*ddmt(r, theta)*math.cos(2*theta) + 1.0*Sigma(r, theta)*ddmt(r, theta) - 2.0*Sigma(r, theta)*denom(r, theta)*math.sin(2*theta) - 1.0*dSt(theta)*denom(r, theta)*math.cos(2*theta) + 1.0*dSt(theta)*denom(r, theta))/(Sigma(r, theta)**2*denom(r, theta)**2)]])


In [40]:
M, r, theta, a = 1.2, 33.26, np.pi / 5.0, 32.34

In [41]:
print(Dcov_metric_tensor(r, theta, a, M))

[[[ 0.00000000e+00 -3.15596369e-04  2.47596254e-02  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  3.52621983e-03 -1.64765829e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  5.36155564e-03 -4.79996520e-01  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  6.65200000e+01 -9.94686805e+02  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  3.52621983e-03 -1.64765829e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.0000

In [42]:
print(Dcot_metric_tensor(r, theta, a, M))

[[[ 0.00000000e+00  3.29256606e-04 -2.57133639e-02  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  2.64496749e-05 -3.86398844e-04  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00 -7.17978732e-03  6.42774815e-01  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00 -2.07432341e-05  3.10177709e-04  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  2.64496749e-05 -3.86398844e-04  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.0000